MVC.Bugdet.App/Controllers/AccountsController.cs
using AutoMapper;
using Domain;
using Infrastructure;
using MVC.Bugdet.App.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace MVC.Bugdet.App.Controllers
{
    public class AccountsController : Controller
    {
        private readonly IAccountRepo<AccountDto, AccountDtoFilter> _accountRepo;
        private readonly ICurrencyRepo<CurrencyDto> _currencyRepo;
        public AccountsController(
            IAccountRepo<AccountDto, AccountDtoFilter> accountRepo,
            ICurrencyRepo<CurrencyDto> currencyRepo)
        {
            _accountRepo = accountRepo;
            _currencyRepo = currencyRepo;
        }

        public async Task<ActionResult> Index()
        {
            List<AccountDto> accountDtos = await _accountRepo.All();
            return View(accountDtos);
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int? id)
        {
            AccountViewModel vm = new AccountViewModel();

            if (id != null)
            {
                AccountDto dto = await _accountRepo.Get(id.Value);
                if (dto == null)
                {
                    return RedirectToAction("Index");
                }

                vm = Mapper.Map<AccountDto, AccountViewModel>(dto);
            }

            await AddCurrencies(vm);

            return View(vm);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<ActionResult> Edit(AccountViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                await AddCurrencies(vm);
                return View(vm);
            }

            AccountDto dto = Mapper.Map<AccountViewModel, AccountDto>(vm);

            if (vm.Id == 0)
            {
                await _accountRepo.Add(dto);
            }
            else
            {
                await _accountRepo.Update(dto);
            }
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Details(int? id)
        {
            AccountViewModel vm = new AccountViewModel();
            if (id != null)
            {
                AccountDto dto = await _accountRepo.Get(id.Value);
                if (dto == null)
                {
                    return RedirectToAction("Index");
                }
                vm = Mapper.Map<AccountDto, AccountViewModel>(dto);
            }

            return View(vm);
        }

        [HttpGet]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id != null)
            {
                AccountDto toDelete = await _accountRepo.Get(id.Value);
                if (toDelete != null)
                {
                    AccountViewModel vm = Mapper.Map<AccountDto, AccountViewModel>(toDelete);
                    return View(vm);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(AccountViewModel vm)
        {
            AccountDto toDelete = Mapper.Map<AccountViewModel, AccountDto>(vm);
            await _accountRepo.Delete(toDelete.Id);
            return RedirectToAction("Index");
        }

        private async Task AddCurrencies(AccountViewModel vm)
        {
            //add currencies
            List<CurrencyDto> currencies = await _currencyRepo.All();
            vm.Currencies = currencies.Select(d => new SelectListItem()
            {
                Text = d.Name,
                Value = d.Id.ToString()
            }).ToList();
        }
    }
}

MVC.Bugdet.App/Controllers/CategoriesController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using Domain;
using Infrastructure;
using MVC.Bugdet.App.Models;
using Repositories;

namespace MVC.Bugdet.App.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly IOperationTypeRepo<OperationTypeDto> _operationTypeRepo;
        public CategoriesController(OperationTypeRepo operationTypeRepo)
        {
            _operationTypeRepo = operationTypeRepo;
        }
        public async Task<ActionResult> Index()
        {
            List<OperationTypeDto> all = await _operationTypeRepo.All();
            List<OperationTypeViewModel> vm =
                Mapper.Map<List<OperationTypeDto>, List<OperationTypeViewModel>>(all);
            return View(vm);
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int? id)
        {
            OperationTypeViewModel vm = new OperationTypeViewModel();

            if (id != null)
            {
                OperationTypeDto toGet = await _operationTypeRepo.Get(id.Value);
                if (toGet == null)
                {
                    return RedirectToAction("Index");
                }
                vm = Mapper.Map<OperationTypeDto, OperationTypeViewModel>(toGet);
            }
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(OperationTypeViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            OperationTypeDto dto = Mapper.Map<OperationTypeViewModel, OperationTypeDto>(vm);
            if (vm.Id == 0)
            {
                await _operationTypeRepo.Add(dto);
            }
            else
            {
                await _operationTypeRepo.Update(dto);
            }
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Details(int? id)
        {
            if (id != null)
            {
                OperationTypeDto toGet = await _operationTypeRepo.Get(id.Value);
                if (toGet != null)
                {
                    OperationTypeViewModel vm = Mapper.Map<OperationTypeDto, OperationTypeViewModel>(toGet);
                    return View(vm);
                }
            }
            return RedirectToAction("Index");

        }

        [HttpGet]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id != null)
            {
                OperationTypeDto toDelete = await _operationTypeRepo.Get(id.Value);
                if (toDelete != null)
                {
                    OperationTypeViewModel vm =
                        Mapper.Map<OperationTypeDto, OperationTypeViewModel>(toDelete);
                    return View(vm);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(OperationTypeViewModel vm)
        {
            OperationTypeDto toDelete = Mapper.Map<OperationTypeViewModel, OperationTypeDto>(vm);
            await _operationTypeRepo.Delete(toDelete.Id);
            return RedirectToAction("Index");
        }
    }
}

MVC.Bugdet.App/Controllers/OperationsController.cs
using AutoMapper;
using Domain;
using Infrastructure;
using MVC.Bugdet.App.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace MVC.Bugdet.App.Controllers
{
    public class OperationsController : Controller
    {
        private readonly IOperationRepo<OperationDto, OperationDtoFilter> _operationRepo;
        private readonly IAccountRepo<AccountDto, AccountDtoFilter> _accountRepo;
        private readonly IOperationTypeRepo<OperationTypeDto> _operationTypeRepo;
        public OperationsController(
            IOperationRepo<OperationDto, OperationDtoFilter> operationRepo,
            IAccountRepo<AccountDto, AccountDtoFilter> accountRepo,
            IOperationTypeRepo<OperationTypeDto> operationTypeRepo
            )
        {
            _operationRepo = operationRepo;
            _accountRepo = accountRepo;
            _operationTypeRepo = operationTypeRepo;
        }
        public async Task<ActionResult> Index()
        {
            List<OperationDto> all = await _operationRepo.All();
            List<OperationViewModel> vm = Mapper.Map<List<OperationDto>, List<OperationViewModel>>(all);
            return View(vm);
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int? id)
        {
            OperationViewModel vm = new OperationViewModel();
            if (id != null)
            {
                OperationDto toEdit = await _operationRepo.Get(id.Value);
                if (toEdit != null)
                {
                    vm = Mapper.Map<OperationDto, OperationViewModel>(toEdit);
                }
            }
            await AddAccountsAndCategories(vm);
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(OperationViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                await AddAccountsAndCategories(vm);
                return View(vm);
            }
            OperationDto dto = Mapper.Map<OperationViewModel, OperationDto>(vm);

            if (vm.Id == 0)
            {
                await _operationRepo.Add(dto);
            }
            else
            {
                await _operationRepo.Update(dto);
            }

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Details(int? id)
        {
            if (id != null)
            {
                OperationDto toGet = await _operationRepo.Get(id.Value);
                if (toGet != null)
                {
                    OperationViewModel vm = Mapper.Map<OperationDto, OperationViewModel>(toGet);
                    return View(vm);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id != null)
            {
                OperationDto toDelete = await _operationRepo.Get(id.Value);
                if (toDelete != null)
                {
                    OperationViewModel vm = Mapper.Map<OperationDto, OperationViewModel>(toDelete);
                    return View(vm);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(OperationViewModel vm)
        {
            await _operationRepo.Delete(vm.Id);
            return RedirectToAction("Index");
        }

        private async Task AddAccountsAndCategories(OperationViewModel vm)
        {
            List<AccountDto> accountDtos = await _accountRepo.All();
            vm.Accounts = accountDtos.Select(d => new SelectListItem()
            {
                Text = d.Name + ' ' + d.Currency.Name,
                Value = d.Id.ToString(),
            }).ToList();

            List<OperationTypeDto> operationTypeDtos = await _operationTypeRepo.All();
            vm.Categories = operationTypeDtos.Select(d => new SelectListItem()
            {
                Text = d.Name,
                Value = d.Id.ToString()
            }).ToList();
        }

    }
}

MVC.Bugdet.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Expenses Overview</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    @*<link href="~/Content/themes/base/selectmenu.css" rel="stylesheet" />
    <link href="~/Content/themes/base/menu.css" rel="stylesheet" />*@
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    @RenderSection("styles", false)
</head>
<body>
    <div class="container bg-light">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href=@Url.Action("Index", "Home")>Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href=@Url.Action("Index", "Accounts")>Accounts <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href=@Url.Action("Index", "Categories")>Categories <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href=@Url.Action("Index", "Operations")>Operations <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="~/Scripts/jquery.js"></script>
    <script src="~/Scripts/jquery-ui.min.js"></script>
    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("dataTable", false)
    @RenderSection("datepicker", false)
    @RenderSection("UI", false)
</body>
</html>